import { JetBrains_Mono, Archivo_Black, Unbounded } from "next/font/google";
import "./globals.css";

const jetBrains_Mono = JetBrains_Mono({
  variable: "--font-jetbrains_Mono",
  subsets: ["latin"],
});

const archivo_Black = Archivo_Black({
  variable: "--font-Archivo_Black",
  subsets: ["latin"],
  weight: ["400"],
});

const unbounded = Unbounded({
  variable: "--font-Unbounded",
  subsets: ["latin"],
});

export const metadata = {
  title: "Wazy",
  description: "Generated by create next app",
};

import Header from "@/components/header";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${jetBrains_Mono.variable} ${archivo_Black.variable} ${unbounded.variable} antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
